Jsaal 36
green-fox-academy/jsa-alexandrite-backend pull request #2
Opened 2019-12-11 02:27 UTC by Aaron-Xiaoxingchen

Can you help me check the set up environment? Thanks

2019-12-11 03:04 UTC, FairyWind requested changes
You need to build a database and initial it in app.js.
Please add an .env.template file also.
Better to test the server when finishing.

2019-12-11 03:04 UTC, FairyWind commented on .gitignore
> +.env
```suggestion
.env
npm-debug.*
```

2019-12-12 09:07 UTC, ikarasz requested changes

2019-12-12 09:07 UTC, ikarasz commented on .eslintrc.json
> +  "rules": {}
we should allow `console.log`

2019-12-12 09:07 UTC, ikarasz commented on App.js
> +console.log('Testing');
pls set up a basic express endpoint here

2019-12-16 10:00 UTC, FairyWind approved these changes

2019-12-17 02:04 UTC, ikarasz requested changes
- do not put the app.js in the root
- read the story specification before creating a pull request: https://jira.greenfox.academy/browse/JSAAL-36, database is needed as well

2019-12-17 02:04 UTC, ikarasz commented on App.js
> +var express = require('express');
do not use var :sob:

2019-12-17 02:04 UTC, ikarasz commented on App.js
> +app.listen(3000, () => {
pls use environemnt variables

2019-12-17 02:04 UTC, ikarasz commented on App.js
> +})
did you run eslint?

2019-12-17 02:04 UTC, ikarasz commented on package.json
> +    "test": "mocha 'tests/**/*.js' --exit",
write a dummy test as well

2019-12-17 02:04 UTC, ikarasz commented on package.json
> +    "start:dev": "nodemon ./App.js"
add nodemon as dependency

2019-12-17 02:04 UTC, ikarasz commented on package.json
> +    "lint": "eslint .",
this will check the node_modules folder as well

2019-12-17 06:28 UTC, FairyWind commented on src/App.js
> +
you should use environment variable from .env here

2019-12-17 06:31 UTC, FairyWind requested changes
fix the port

2019-12-17 08:08 UTC, FairyWind approved these changes

2019-12-17 08:29 UTC, ikarasz requested changes

2019-12-17 08:29 UTC, ikarasz commented on .eslintrc.json
> +      "browser": true,
do you wanna run the backend in the browser? :)

2019-12-17 08:29 UTC, ikarasz commented on package.json
> +    "start": "node .src//App.js",
are you sure this will work?

2019-12-17 08:29 UTC, ikarasz commented on package.json
> +    "assert": "^2.0.0",
is it really a production dependency?

2019-12-17 08:29 UTC, ikarasz commented on package.json
> +    "mocha": "^6.2.2",
is it really a production dependency?

2019-12-17 08:29 UTC, ikarasz commented on package.json
> +    "nodemon": "^2.0.2",
is it really a production dependency?

2019-12-17 08:29 UTC, ikarasz commented on src/App.js
> +const { PORT } = process.env;
variable declaration should go to the top of the file

2019-12-17 09:39 UTC, ikarasz approved these changes

2019-12-17 09:39 UTC, merged