JSAAL-17 Add investments value card
green-fox-academy/jsa-alexandrite-backend pull request #4
Opened 2019-12-19 07:16 UTC by FairyWind

2019-12-19 08:09 UTC, ajaxjiang96 requested changes

2019-12-19 08:09 UTC, ajaxjiang96 commented on src/controller/investments.js
> +    return res.status(200).json(userData);
You don't need to specify status code here and you can just use `res.send`
```suggestion
    return res.send(userData);
```

2019-12-19 08:09 UTC, ajaxjiang96 commented on src/controller/investments.js
> +  return res.status(404).send('User not found.');
```suggestion
  return res.sendStatus(404);
```

2019-12-19 08:17 UTC, ajaxjiang96 approved these changes

2019-12-20 02:33 UTC, ikarasz requested changes

2019-12-20 02:33 UTC, ikarasz commented on src/controller/investments.js
> +investments.use(express.json());
json middleware is not needed, it is for parsinf request body

2019-12-20 02:33 UTC, ikarasz commented on src/controller/investments.js
> +  const userData = userInvestments.find((data) => data.user_id === uid);
please use camelCase

2019-12-20 02:58 UTC, ikarasz approved these changes

2019-12-20 02:59 UTC, merged