JSAAL-66 investments backend
green-fox-academy/jsa-alexandrite-backend pull request #7
Opened 2019-12-25 09:41 UTC by FairyWind

2019-12-26 08:40 UTC, ajaxjiang96 approved these changes

2019-12-26 08:40 UTC, ajaxjiang96 commented on src/controller/investments.js
> +  const user = await User.findById(_id, 'investments').exec();
```suggestion
  const user = await User.findById(_id, 'investments');
```

2020-01-06 07:23 UTC, ikarasz commented on src/controller/investments.js
> +      return res.sendStatus(401);
does this mean authentication error?

2020-01-06 07:23 UTC, ikarasz commented on src/controller/investments.js
> +    return res.sendStatus(404);
how can we get 404 with a valid token? We generate the token during login, which means there _is_ a user with this id.

2020-01-07 06:11 UTC, ikarasz commented on src/controller/users.js
> +      const accessToken = jwt.sign(user.toJSON(), secret);
Dont we want to set expiry date for the tokens? It is really dangerous. I would go with an increased expiry date instead

2020-01-07 06:11 UTC, ikarasz commented on src/controller/investments.js
> +    const user = await User.findById(_id, 'investments');
are you sure we don't need to transfer the data? Don't we have an `_id` in the user document? All the keys are in `camelCase` and has only the mandatory fields? Aren't there any mongo related fields in the document?

2020-01-08 04:17 UTC, ikarasz requested changes

2020-01-08 04:17 UTC, ikarasz commented on src/controller/investments.js
> +    const result = user.investments.map((stock) => {
how about something like this?
```js
user.investments.map(({ _id, ...stock }) => ({ id: _id, ...stock }))
```

2020-01-08 06:01 UTC, ikarasz approved these changes

2020-01-08 06:01 UTC, merged